version: '3.3'
services:

  reddcoin-server:
    container_name: reddcoin-server
    image: reddcoincore/server:3.10.2
    restart: always
    volumes:
    - /root/.reddcoin/:/root/.reddcoin/
    networks:
     net1:
       aliases:
        - alias2
    environment:
      - RPC_SERVER=1
      - RPC_USERNAME=reddrpc
      - RPC_PASSWORD=7vWAWLDK4ioT3MHX8Gym8Bc5uj6T4aa1kY7KYaTFgcJy
      - RPC_PORT=45443
      - RPC_ALLOW_IP=127.0.0.1/0

  reddcoin-seeder:
    container_name: reddcoin-seeder
    image: reddcoincore/seeder:latest
    restart: always
    networks:
     net1:
       aliases:
        - dnsseed
    volumes:
    - /root/.reddcoin/:/root/.reddcoin/
    ports:
     - 0.0.0.0:53:53/udp
    links:
      - reddcoin-server
    environment:
      - HOSTNAME=dnsseed01.redd.ink
      - IPADDRESS=104.236.140.62

networks:
  net1:
