version: "3.6"
services:

  reddcoin-server:
    container_name: reddcoin-server
    image: reddcoincore/server:latest
    build: ./server
    ports: 
      - "45443:45443"
      - "45444:45444"
# Use custom volume for data
#    volumes:
#      - "./.reddcoin:/root/.reddcoin"
# Inject Bootstrap for faster Startup
#      - "./bootstrap:/root/bootstrap"
    environment:
      - RPC_SERVER=1
      - RPC_USERNAME=username
      - RPC_PASSWORD=password
      - RPC_PORT=45443
      - RPC_ALLOW_IP=0.0.0.0/0

  reddcoin-compiler:
    container_name: reddcoin-compiler
    image: reddcoincore/compiler:latest
    build:
      context: .
      dockerfile: ./compiler/Dockerfile

  reddcoin-seeder:
    container_name: reddcoin-seeder
    image: reddcoincore/seeder:latest
    build:
      context: .
      dockerfile: ./seeder/Dockerfile
    ports:
     - 53:53/udp

  reddcoin-mysql:
    container_name: reddcoin-mysql
    image: mysql/mysql-server:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: r3ddcoint1pb0t
      MYSQL_ROOT_HOST: '%'
    volumes:
      - "./dbdata:/var/lib/mysql/"

  reddcoin-twittertipbot:
    container_name: reddcoin-twittertipbot
    image: reddcoin-twittertipbot
    restart: always
    build:
      context: .
      dockerfile: ./tipbots/twitter/Dockerfile
    ports:
      - "127.0.0.1:3000:3000"
    links:
      - reddcoin-mysql:reddcoin-mysql
    volumes:
      - "./SocialTipBot:/root/SocialTipBot"
      - "./.reddcoin:/root/.reddcoin"
