FROM ubuntu:20.04
LABEL maintainer="info@reddcoin.com"
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /root

ENV REDDCOIN_VERSION "3.10.3"

COPY ./bin/reddcoin-${REDDCOIN_VERSION} /usr/local/bin
RUN mkdir -p /root/.reddcoin
RUN find /usr/local/bin -type f -exec chmod u+x {} \;

ENV RPC_SERVER 1
ENV RPC_USERNAME rpcusername
ENV RPC_PASSWORD rpcpassword
ENV RPC_PORT 45443
ENV RPC_ALLOW_IP 0.0.0.0/0
ENV TESTNET=0

COPY ./setup.sh .
RUN chmod u+x /root/setup.sh

EXPOSE 45443 45444 55443 55444

CMD [ "/root/setup.sh" ]
