version: "3.6"
services:

# Setup 3 reddcoin core testnet nodes

  reddcoin-server1:
    container_name: reddcoin-server1
    image: reddcoincore/server:latest
    restart: always
    build:
      context: ./server
      dockerfile: ./Dockerfile-testnet
    ports:
      #      - "55443:55443"
      - "55444:55444"
    # Use custom volume for data
    volumes:
      - "./.reddcoin1:/root/.reddcoin"
    # Inject Bootstrap for faster Startup
      - "./bootstrap:/root/bootstrap"
    environment:
      - RPC_SERVER=1
      - RPC_USERNAME=reddrpc
      - RPC_PASSWORD=Ho8vezZzgi5zRbg36bJTKmXRhEuExJDcJWLBrRdxpkze
      - RPC_PORT=55443
      - TESTNET=1
      - RPC_ALLOW_IP=0.0.0.0/0
      - BOOTSTRAP=testnet-blockchain-Jul-16-2021.zip

  reddcoin-server2:
    container_name: reddcoin-server2
    image: reddcoincore/server:latest
    restart: always
    build:
      context: ./server
      dockerfile: ./Dockerfile-testnet
    #    ports:
    #      - "55443:55443"
    #      - "55444:55444"
    # Use custom volume for data
    volumes:
      - "./.reddcoin2:/root/.reddcoin"
    # Inject Bootstrap for faster Startup
      - "./bootstrap:/root/bootstrap"
    environment:
      - RPC_SERVER=1
      - RPC_USERNAME=reddrpc
      - RPC_PASSWORD=Ho8vezZzgi5zRbg36bJTKmXRhEuExJDcJWLBrRdxpkze
      - RPC_PORT=55443
      - TESTNET=1
      - RPC_ALLOW_IP=0.0.0.0/0
      - BOOTSTRAP=testnet-blockchain-Jul-16-2021.zip

  reddcoin-server3:
    container_name: reddcoin-server3
    image: reddcoincore/server:latest
    restart: always
    build:
      context: ./server
      dockerfile: ./Dockerfile-testnet
    #    ports:
    #      - "55443:55443"
    #      - "55444:55444"
    # Use custom volume for data
    volumes:
      - "./.reddcoin3:/root/.reddcoin"
    # Inject Bootstrap for faster Startup
      - "./bootstrap:/root/bootstrap"
    environment:
      - RPC_SERVER=1
      - RPC_USERNAME=reddrpc
      - RPC_PASSWORD=Ho8vezZzgi5zRbg36bJTKmXRhEuExJDcJWLBrRdxpkze
      - RPC_PORT=55443
      - TESTNET=1
      - RPC_ALLOW_IP=0.0.0.0/0
      - BOOTSTRAP=testnet-blockchain-Jul-16-2021.zip

  reddcoin-electrumx:
    container_name: reddcoin-electrumx
    image: reddcoin-electrumx
    build:
      context: ./docker-electrumx
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - ./electrumx-data:/data
    environment:
      - DAEMON_URL=http://reddrpc:Ho8vezZzgi5zRbg36bJTKmXRhEuExJDcJWLBrRdxpkze@reddcoin-server1
      - COIN=ReddcoinTestnet
      - NET=testnet
      - COST_HARD_LIMIT=100000
    ports:
      - 0.0.0.0:51002:50002
    depends_on:
      - reddcoin-server1

  reddcoin-blockstore:
    container_name: reddcoin-blockstore
    image: reddcoin-blockstore
    restart: always
    build:
      context: ./reddstack/blockstore
      dockerfile: ./Dockerfile
#    ports:
#      - "127.0.0.1:6264:6264"
    depends_on:
      - reddcoin-server3
    volumes:
      - "./.blockstore:/root/.blockstore"
      - "./.reddstore-client:/root/.reddstore-client"
      # Inject Bootstrap for faster Startup
      - "./bootstrap:/root/bootstrap"
    environment:
      - BLOCKSTACK_TESTNET=1
      - BLOCKSTACK_DEBUG=1
      - RPC_USERNAME=reddrpc
      - RPC_PASSWORD=Ho8vezZzgi5zRbg36bJTKmXRhEuExJDcJWLBrRdxpkze
      - RPC_PORT=55443
      - BOOTSTRAP=testnet-blockstore-Aug-02-2021.zip

  reddcoin-reddstack-rest:
    container_name: reddcoin-reddstack-rest
    image: reddcoin-reddstack-rest
    restart: always
    build:
      context: ./reddstack/reddstack-rest
      dockerfile: ./Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - reddcoin-blockstore
    volumes:
      - "./.reddstore-client:/root/.reddstore-client"
    environment:
      - BLOCKSTACK_TESTNET=1
      - BLOCKSTACK_DEBUG=1