name: all

on:
  push:
    branches:
    - master

jobs:

  build-server:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
    - name: Build Docker Image
      run: docker build ./server --tag reddcoincore/server:latest
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Push Docker Image
      run: docker push reddcoincore/server:latest

  build-compiler:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
    - name: Build Docker Image
      run: docker build ./compiler --tag reddcoincore/compiler:latest
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Push Docker Image
      run: docker push reddcoincore/compiler:latest

  build-seeder:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
    - name: Build Docker Image
      run: docker build ./seeder --tag reddcoincore/seeder:latest
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Push Docker Image
      run: docker push reddcoincore/seeder:latest
